language: python
python:
  - "3.6"
env:
  - "SECRET='My-secret-a-long-string'", "APP_SETTINGS='development'"
services:
  - postgresql

before_script:
  - psql -c "create database test_db;" -U postgres
  

# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"

# command to run tests
script: nosetests --with-coverage --cover-package=app

after_success: coveralls

